### ISSUE TITLE
Soundflower not working in OS X EL Captain

### ISSUE THREAD

**Issue by Superjustinbros** [RogueAmoeba/Soundflower#44]
Ever since a few days ago when I upgraded to OS X El Captain, I've been having problems trying to run SoundFlower. It keeps claiming the program is "not installed!" despite me attempting to download and install it twice by now.

**Comment by mattingalls** [comment]
try this version: https://github.com/mattingalls/Soundflower/releases/tag/2.0b2

**Comment by raystation** [comment]
I came here to post this, this release seems restore functionality! Thanks.

**Comment by Superjustinbros** [comment]
Thanks, though it appears the install process freezes on this step.
![screen shot 2015-10-26 at 1 42 48 pm](https://cloud.githubusercontent.com/assets/4167951/10737262/91ed4bfe-7be7-11e5-8f2a-ad0c8826475b.png)

**Comment by Superjustinbros** [comment]
Well it did download, but it still thinks that it's not installed (with no icon in the Applications folder or topbar), though it shows the sound channels in System Settings.
![screen shot 2015-10-26 at 2 10 58 pm](https://cloud.githubusercontent.com/assets/4167951/10737998/909603a0-7beb-11e5-81c1-0b98d3fa5db3.png)
There were also no prompts to restart the system.

**Comment by mattingalls** [comment]
that's it!  if you want to use soundflowerBED you can use the older version with this version of soundflower. (but creating a Multi-output device in the AudioMIDISetup Utility app can also be used in many cases)

**Comment by Superjustinbros** [comment]
...Can you describe it in more detail? Your description confuses me a bit.

**Comment by mattingalls** [comment]
this guy made a video: https://www.youtube.com/watch?v=kyS7UG3wmb0

**Comment by Superjustinbros** [comment]
That didn't help at all.
What I want to do is just have i so it plays and records only the audio form the computer and not it alongside the auto form the external microphone.
I do not do streaming and I use Soundflower solely to record sounds and music from online using Audacity, but ever since the El Captain "upgrade", I cannot find anything to fix it.

In a nutshell, any and all audio from Soundflower's channels are 100% mute for me.

**Comment by mattingalls** [comment]
did you check soundflower's mute and volume levels? (your screenshot here only shows the internal speakers) by the way, i'm going to remove those settings in the next version to prevent this kind of accidental muting from happening

**Comment by Superjustinbros** [comment]
How can I check them if it doesn't show up under Applications or the top-bar?

**Comment by mattingalls** [comment]
system preferences or audio midi setup

**Comment by Superjustinbros** [comment]
Nothing happens.
![screen shot 2015-10-26 at 10 53 08 pm](https://cloud.githubusercontent.com/assets/4167951/10748227/646e604e-7c34-11e5-9c0e-31bbfe40a314.png)
![screen shot 2015-10-26 at 10 53 18 pm](https://cloud.githubusercontent.com/assets/4167951/10748230/667780b4-7c34-11e5-91c0-1c16c66e2a80.png)

**Comment by mattingalls** [comment]
you certainly don't want to set both input and output to Soundflower -- that would create a feedback loop and i wouldn't be surprised if the OS catches that and shuts it down.   so what you want to do is set default system output to Soundflower. and default input and system sounds to Built-in.  Then reboot just to be on the safe side.  then open audacity and set its input to Soundflower and its output to Built-in.

**Comment by ghost** [comment]
Hi mattingalls, I'm actually having a similar issue to Superjustinbros and I have followed your advise to the letter. Even though everything is set up as advised, Soundflower is not recording the sound at all. Have tried a fresh install after deleting the original, and rebooted after each set-up. Not sure what else to do to get this to work! Have also tried other solution to set it up as a Multi-Output Device, but that doesn't seem to do anything either. 

Thanks in advance for any help you are able to provide

**Comment by Superjustinbros** [comment]
Well I sort of figured out how to get it work via Audacity.
If you set the speakers and recording source to Soundflower; it still records what sounds would usually be playing (as you can hear them when switching back to normal speakers) but absolutely nothing comes out of the speakers.

**Comment by mattingalls** [comment]
@Superjustinbros -- ok that confirms to me that the install DOES work and you just haven't set things up quite right (aka "user error - probably same with @lazergirl21) -- Soundflower has no "speakers" or "Recording" capabilities -- all it does is take audio in and spit it out!  Since i don't know y'all's exact scenario, here is an example: 

Say i want to play some audio in iTunes, but record it in Quicktime while listening to it out of the built-in speakers.  Here is how i would set it up:
- in iTunes
  - start playing audio
- Open Audio MIDI Setup:
  - hit the '+' button in the bottom left corner and select "Create Multi Output Device"
  - in the the panel that appears on the right, select "Built-in Output" AND "Soundflower (2ch)"
  - then hit the button with the gear icon bottom left and select "use this device for sound output"
     (you should still be hearing your iTunes output -- it is now going to both Soundflower and the built-in speakers)
- In Quicktime:
  - create a new audio recording 
  - in the popup menu next to record button select "Soundflower (2ch)" as the input
  - (you should now see record levels changing) 
  - hit record!

**Comment by lingenfr** [comment]
@mattingalls. (I'm reposting in this thread as it seems to be a better fit). Matt, first thanks for your work. I've used SF and the audiomixer app for years on my MBA. I got a new MB and HDMI monitor (since my TB displays are useless). I can't control the volume on the Display from the menu and had hoped to use SF. Others said it worked, but no joy for me. I am on El Capitan. I believe I installed SF (your version above) correctly and I have two SF devices in my output list. When I select either of them, I get no sound. I tried @worldsfinestvideo's method. Obviously, that doesn't work for what I am trying to do. Am I out of luck or doing something wrong. I don't have a Soundflower folder/icon in my Applications folder and no Soundflowerbed icon on my task bar. I have tried all of the solutions proposed in this thread. No joy. Thanks.

**Comment by mattingalls** [comment]
you can take your chances with the older version of soundflowerbed (just make sure to _not_ install the old version of soundflower!) i am not supporting soundflowerbed at this time

**Comment by lingenfr** [comment]
Thanks. Is there a compiled version for OS X available somewhere? For folks like me, I'm not sure how it works for others, the multi-output device doesn't not solve my problem. I need to take in the system sound, process through SF for volume control and output via HDMI. The multi-output device does not accomplish that (unless I am missing something).

**Comment by mattingalls** [comment]
there's probably one from rogue amoeba

**Comment by lingenfr** [comment]
If so, I don't see it. I only see the source code. Another fellow (TNTsomething) posted a 1.6.7 version that included SFB. I don't know how or if it is possible to parse SFB out. I assume it is not. Should I uninstall your latest version, install the the 1.6.7 version and then install yours over the top? If not, I think I am just going to use external speakers with a volume knob. Very annoying that Apple can't sort this out. The dipsticks only allow minidisplayport and HDMI yet they give you no way to control the sound. Brilliant.

**Comment by mattingalls** [comment]
yes use that 1.6.7 version... there should be an "advanced options" button in the soundflower installer that lets you only install the bed.

**Comment by lingenfr** [comment]
No joy. I couldn’t find an “advanced options” button and the 1.6.7 install fails. For the time being, I uninstalled everything. Sounds like my use of SF must not be that popular. However, you also need this same setup to use the EQ the way I used SF previously. The multi-output is good for dual-inline applications, but not so hot for single-inline. I am pretty sure SFB is the only way to get there. I am researching external speakers with a volume knob. Very annoying. Cheers.

**Comment by mattingalls** [comment]
sorry the button is called "customize" (appears in the "installation type" stage)

**Comment by lingenfr** [comment]
Not in the TNT… 1.6.7 package. The only option during the Installation Type stage is Change Install Location. I will check the 1.6.6 package.

**Comment by rca** [comment]
Hey @mattingalls, thanks for all the support here.  My scenarios is quite simple: I want to control HDMI audio volume as [described in this blog post](http://www.mattmontag.com/music/enable-mac-volume-control-for-hdmi-and-displayport-audio-devices).  Do you mind outlining this process with SoundFlower 2.0 + AudioMidi Setup, sans soundflower _BED_.  Thank you!

**Comment by KarimGaliaskar** [comment]
https://github.com/crmne/Soundflower/releases/tag/1.6.7-mavericks-p1 

Just will leave it here. Worked for me )

**Comment by ghost** [comment]
@mattingalls Hi Matt! apologies for bothering...
I've tried to setup soudflower as per your input, but i still have the issue of the mute output. I do realise that the option "use this device for sound output" is greyed out, despite the fact that the new multi-output device is created... Where am i doing wrong? Thank you in advance!

**Comment by mattingalls** [comment]
sounds like you made an "aggregate device" instead of "multi output device"

**Comment by Democide** [comment]
Woo. Thanks guys. I finally got it working and am now able to record the screen audio together with the screen. However some clicking can be heard when DRIFT CORRECTION is enabled in the multi-output device.

**Comment by alexreg** [comment]
I don't understand: why does Soundflower require that the output volume for its device be non-zero in order for it to _record input_?

**Comment by suncrud** [comment]
@mattingalls sorry for the bother, I had a question regarding the input volume. I believe that I had done all right but 
<img width="653" alt="screen shot 2016-07-26 at 6 06 33 am" src="https://cloud.githubusercontent.com/assets/7371023/17134212/582489d6-52f7-11e6-8bdb-9d43aedbcc0b.png">

my volume level is ridiculously small when I record it
<img width="289" alt="screen shot 2016-07-26 at 6 06 15 am" src="https://cloud.githubusercontent.com/assets/7371023/17134247/7d5061e4-52f7-11e6-9fbb-79f3778d2943.png">
<img width="668" alt="screen shot 2016-07-26 at 6 08 54 am" src="https://cloud.githubusercontent.com/assets/7371023/17134252/82db0934-52f7-11e6-9ce5-17ab5d6b7bf1.png">

Any idea on how I should solve this? Thanks for your time. Cheers!

**Comment by mattingalls** [comment]
in AudioMIDISetup, select Soundflower and make sure all the volume sliders are at full volume.

**Comment by bunnysoup** [comment]
Has anybody else seen 2.02b stop working after upgrading to OSX 10.11.6? I have two systems running Soundflower 2.02b, no SFBed on either system. The only difference is that the system that works is at 10.11.5 (kernel 15.5.0) and the one that doesn't work (anymore) is at 10.11.6 (kernel 15.6.0). No wonky nvram settings on either system. SIP disabled on both. Kext loads OK, all audio settings & MIDI available but no output with Soundflower. Using for plain audio out with AULab on both systems.

**Comment by mattingalls** [comment]
it's working for me on 10.11.6..

**Comment by bunnysoup** [comment]
@mattingalls Any suggestion on what to look for?

Is there some debug mode for soundflower or coreaudio that might be useful here? I've played a bit with kextutil to generate symbols, and get nice clean load progress. Maybe nothing useful there. Otherwise going to see if a local build works ....

**Comment by ghost** [comment]
Hi Matt, thank you for continuing to support this wonderful app. 

As some others have asked, my input signal seems weak, despite both input and output sliders are at full volume. 

I'm trying to play an audio file of an interview through Soundflower (2ch), input it through Soundflower (2ch) to let the Google Voice Typing on Google Docs hear the interview and to transcribe it for me. It works with a very, very loud voice, or segments where the voice is very loud and clear, but Google tells me that it cannot 'hear' the voice where the voice is not so loud (even though the supposedly 'quieter' voice is still loud enough to hurt my ears if I play it through headphone output). 

Do you perhaps know why the sound input volume is somehow reducing the output volume level? Thank you in advance for your help.

**Comment by timotei** [comment]
@bunnysoup A local build (only) works for me on El Capitan.

@mkar10 You should create another issue so it's tracked properly.

**Comment by xiaose** [comment]
BTW, how to know which version on SoundFlower is now installed in system, 1.6.6b or 2.0.b2? Because I have reinstalled it many times and now don't know which version is installed

**Comment by brockap3** [comment]
In case someone is still having this issue, just today I was having issues getting quicktime to listen to sound flower while using the audio midi setup, despite having volume up for all output devices using the audio buttons. Turns out inside the audio midi setup, the sound flower individual channels 1 and 2 were 0 but the master channel was non-zero. Once I changed those channels to non-zero, everything worked just fine. Hope this helps.
![screen shot 2016-09-17 at 08 51 10](https://cloud.githubusercontent.com/assets/9257659/18608312/3873351a-7cb4-11e6-844b-7ce2c28ac00b.png)
![screen shot 2016-09-17 at 08 54 01](https://cloud.githubusercontent.com/assets/9257659/18608320/4f44f634-7cb4-11e6-89c7-5023014a1dc9.png)

**Comment by zenvendof** [comment]
Yes agree with @brockap3, make sure you max out all the volume for Master, Channel 1 & 2 for INPUT/OUTPUT on Soundflower (2ch), otherwise you hear nothing.  Thanks @mattingalls, been using it for ages just upgraded to 2.0b2.

**Comment by Superjustinbros** [comment]
Seems like my current Soundflower setup no longer works as of 10.12; the Soundflower 2ch channel is mute and not recorded by Audacity.

**Comment by Allur4** [comment]
I followed your instructions with playing itunes and setting up the device. I checked all the sound settings. Instead of playing normal sound, it plays a weird screeching sound whenever I try to switch to the multi-output device. Any help would be greatly appreciated

**Comment by mattingalls** [comment]
@Allur4 -- sounds like feedback -- you probably have soundflower set to output and input

**Comment by Allur4** [comment]
It doesn't let me set it to both

**Comment by mattingalls** [comment]
@Allur4 what app are you using to capture the iTunes output?  you need an app (like QuickTime) that lets you set input and/or output devices (and not just using the system defaults, because if soundflower is set to system input and multi-device is set to system output, you will get feedback! )

**Comment by Allur4** [comment]
<img width="433" alt="screenshot 2016-10-06 07 47 32" src="https://cloud.githubusercontent.com/assets/22641316/19151156/306e2c78-8b99-11e6-9ad7-32b97ae12c1c.png">
<img width="649" alt="screenshot 2016-10-06 07 46 59" src="https://cloud.githubusercontent.com/assets/22641316/19151158/3233e214-8b99-11e6-8930-5e3ee12ed820.png">

**Comment by Allur4** [comment]
OH I see
I'm an idiot lol. Let me try switching it up

**Comment by Allur4** [comment]
No it didn't work. Don't I want the input for quicktime to be the multi-output device?

**Comment by mattingalls** [comment]
@Allur4: soundflower should be the QT input.  what you have in the screenshot looks good.  when are you getting the "screech"? note that that slider in the QT record window is OUTPUT volume -- and you should keep that set all the way to zero (or you will get feedback!).  the multi-output device will automatically send the audio to your computer's speaker anyway so you monitor that way... (that's why you are using it!) that meter in QT doesn't really show any soft sounds, so don't be too concerned if you don't see anything.  best way to see if it works is to just record something and play it back...

**Comment by goodnamesalltaken** [comment]
I have been using Quicktime with Soundflower 2.0b2 (with Mac OS Sierra) to make screen recordings from internal speakers. It worked fine for 3 days but now all of a sudden my recordings lack sound. I haven't added or upgraded any programs. I don't _think_ I've changed my method, but I wouldn't be surprised to find operator error at play. 

Here is the method I used to set up my recordings:
1.Install Soundflower.

2.Go to Audio MIDI Setup

3.Click the '+' sign at the bottom left of the window and select 'Create Multi-Output Device'

4.Check the boxes at the 'Use' column next to Built-In Output and Soundflower 2ch(64ch is not recommended).Also tick the box in the 'Drift Correction' column for Built-In Output.

5.Adjust your volume to maximum.

6.Go to System Preferences->Sound->Output and choose your Multi-Output device.

I tried uninstalling and re-installing Soundflower. I rebooted after both uninstall and re-installation. I also tried uninstalling and reinstalling the Multi-output Device. 

If I record using internal microphone instead I get sound but it is fuzzy (as though I were recording the sound that comes out of my computer speakers with a handheld device). 

What am I missing? I have attached screen shots of my set up. 

![screen shot 2016-11-07 at 12 26 34 am](https://cloud.githubusercontent.com/assets/23317941/20067063/5e6ad38e-a4d9-11e6-9c4b-26eff57df862.png)
![screen shot 2016-11-07 at 12 25 17 am](https://cloud.githubusercontent.com/assets/23317941/20067064/5e6eae00-a4d9-11e6-9481-de3241df083f.png)
![screen shot 2016-11-07 at 12 21 42 am](https://cloud.githubusercontent.com/assets/23317941/20067065/5e7a889c-a4d9-11e6-8f5b-76564ef30ecc.png)
![screen shot 2016-11-07 at 12 17 01 am](https://cloud.githubusercontent.com/assets/23317941/20067066/5e8609e2-a4d9-11e6-881d-d3d9020ec5d9.png)
![screen shot 2016-11-07 at 12 16 44 am](https://cloud.githubusercontent.com/assets/23317941/20067067/5e85de9a-a4d9-11e6-8651-7ed7b3699f73.png)

**Comment by mattingalls** [comment]
@goodnamesalltaken you have Soundflower (2ch) mute checked -- btw, i'm going to remove this in the next release it is a cause of too many user errors

**Comment by goodnamesalltaken** [comment]
@mattingalls OH MY GOD I can't believe I did that. I can't believe it! I just unchecked it and my problem is solved. Operator error, the bane of my existence...

Thank you so much. 

EDIT: actually this now works for me using Soundflowerbed, which I tried after I couldn't get the new Soundflower version to work. I will revert to the new version and make sure I uncheck the mute button. Yikes. Thanks again.

**Comment by Beth17** [comment]
I use aggregate device instead of multi-output device and it has been working for months on el capitan however now the logo does not pop up in my top bar so I can't chose built it output and therefore cannot hear in game sound! Does anyone know how I can get it to work so I can record my voice and the in game sound? Thanks! 
<img width="652" alt="screen shot 2016-11-14 at 13 14 12" src="https://cloud.githubusercontent.com/assets/23453990/20266173/ddd2fc6c-aa6c-11e6-9fa6-9e32e44de5d7.png">

This is the video I used to set it up years ago: https://www.youtube.com/watch?v=Q2d4JEwMCCQ

**Comment by ErikP1988** [comment]
Since today my Soundflower is suddenly not working anymore (El Capitan). I'm not getting an input signal somehow. What's wrong?

<img width="590" alt="schermafbeelding 2017-01-14 om 15 41 27" src="https://cloud.githubusercontent.com/assets/25120238/21955674/20e34826-da70-11e6-8a69-3164e36444b1.png">
<img width="663" alt="schermafbeelding 2017-01-14 om 15 41 46" src="https://cloud.githubusercontent.com/assets/25120238/21955676/20e43d4e-da70-11e6-8e84-5f1297a499fd.png">
<img width="822" alt="schermafbeelding 2017-01-14 om 15 42 28" src="https://cloud.githubusercontent.com/assets/25120238/21955675/20e38ca0-da70-11e6-8681-fcf1361d04ce.png">

**Comment by mattingalls** [comment]
@ErikP1988 in AudioMIDISetup, click on Soundflower (2ch) and make sure the mute buttons are not on or the volume sliders down

**Comment by marchvet** [comment]
I have tried SF 1.6.6 and 2.0 and still cannot get audio to record along with my video.  I have tried every configuration listed above and it doesn't work.  My OS is: Yosemite 10.10.5.  Ended up removing SF completely from my system as I am not sure which version to use.  Is 2.0 ok?

**Comment by mattingalls** [comment]
@ErikP1988 i didn't see those screenshots before.  but it looks like you created a potential feedback loop by having SF set to system input and system output (by way of the multi output device).  Try setting the mac's microphone to the system input.

**Comment by mattingalls** [comment]
@marchvet if you give more details i can try to help.  also look in Audio MIDI Setup and make sure nothing is muted, volume levels are up, no feedback loops, etc

**Comment by BAKASHIII** [comment]
I have this same issue
Well it did download, but it still thinks that it's not installed (with no icon in the Applications folder or topbar), though it shows the sound channels in System Settings.
screen shot 2015-10-26 at 2 10 58 pm
There were also no prompts to restart the system.
I really tried everything

**Comment by mattingalls** [comment]
@BAKASHIII -- i think you are looking for the "Soundflowerbed" app, which isn't supported anymore.  (soundflower itself is just an audio device)  You can do most of what soundflowerbed did now with a multi-output device.  read my example how to use it here: https://github.com/mattingalls/Soundflower/releases/tag/2.0b2

**Comment by sillygumpee** [comment]
I am setting up a Twitch channel. soundflower came recommend from many streamers. They all have the icon at the top of the screen to change their settings easily. From this long thread that I am reading, it has become very confusing. 

Is there a tutorial that has been made or a video that someone has created showing how to get this program to actually work now? 

I am trying to get soundflower to pick up the sound from my xbox through a capture card. I have soundflower bed selected but I am not getting any sound on my streams. This is becoming very frustrating.

**Comment by mattingalls** [comment]
@sillygumpee -- the icon at the top of the screen is the soundflowerBED app, which isn't supported anymore.  and you might not need soundflower at all -- what exactly are you trying to do?

**Comment by sillygumpee** [comment]
Xbox One - Elgato HD60 - Mac. Sound from Xbox One picked up by Soundflower and pushed to OBS. From OBS to Twitch.

**Comment by chrisbaz** [comment]
I have been through this in detail but still cannot get Audacity to work in El Capitan 10.11.6. on an iMac. (It all worked before the parade to El Capitan)

I have now loaded onto my MacBook Air which is only Sierra.  Here I have managed to make it work, though it will only do so if Output is set to soundflower 2 ch, this I cannot monitor the sound while I am recording.  I had this problem in the past and cannot remember how to resolve it - I have also googled a solution but can find nothing.

I look forward to the next Audacity upgrade...

**Comment by chrisbaz** [comment]
And another thing... with Sierra, there is no option for Multi-output device in System Preferences as there is in El Capitan

**Comment by edkay360** [comment]
Having followed the advice in this thread I am unable to get the sound to record when doing a screen recording in QuickTimePlayer. The sound bar at the top of the screen recording window doesn't register any sound and there is none when I record the screen.
Soundflower downloaded from https://github.com/mattingalls/Soundflower/releases/tag/2.0b2
I am running OS X Yosemite 10.10.5
<img width="289" alt="screenshot 2017-03-15 16 00 19" src="https://cloud.githubusercontent.com/assets/26439463/23957947/90112c48-0998-11e7-9d90-277be8c2b67a.png">
<img width="977" alt="screenshot 2017-03-15 15 59 07" src="https://cloud.githubusercontent.com/assets/26439463/23957969/9dfc9090-0998-11e7-93a2-584542d7edc6.png">
<img width="980" alt="screenshot 2017-03-15 15 58 50" src="https://cloud.githubusercontent.com/assets/26439463/23957968/9dfc4c66-0998-11e7-8d8b-02589633f734.png">
<img width="669" alt="screenshot 2017-03-15 15 57 58" src="https://cloud.githubusercontent.com/assets/26439463/23957966/9df9aa24-0998-11e7-8c26-5169ad8aa762.png">
<img width="669" alt="screenshot 2017-03-15 15 57 53" src="https://cloud.githubusercontent.com/assets/26439463/23957971/9e9e4692-0998-11e7-977f-f0c29529b5e8.png">
<img width="976" alt="screenshot 2017-03-15 15 57 18" src="https://cloud.githubusercontent.com/assets/26439463/23957967/9dfba4e6-0998-11e7-9a90-68396e278cb8.png">

Many thanks for any help.

**Comment by mattingalls** [comment]
@edkay360 are you setting the input in the Quicktime record window to Soundflower? (the popup menu next to the record button).   i would also suggest to turn up all Soundflower's volume sliders in AudioMIDISetup to maximum.

**Comment by edkay360** [comment]
Yes, I had the input set. It was Soundflower's volume sliders in AudioMIDISetup. It seems I needed the master and both of 1 and 2 set to max for both input and output.
Thank you very much for your help

**Comment by mattingalls** [comment]
ok good to know!   i actually have a new version with the volume and mute control taken out -- it's a cause of too many problems.  haven't released it yet because i want to make a helper app that will have a monitoring device with volume slider there (that won't change the soundflower volume itself, just the monitor level)

**Comment by sommerdi** [comment]
I have problems with randomly disruption with noise. Every 2min....
I tested  this with itune, pd & logicx for 2ch & 64ch.
My system is MBP 15" retina 10.11.6 .. any support is more than welcome

**Comment by cynclical** [comment]
I know this place is kind of dead, but I want to know why doesn't soundflower work in a Steam Game?

**Comment by cynclical** [comment]
Never mind, it seems to me that you have to have the game running after starting up Quickplay, weird ain't it?

**Comment by iMactoo** [comment]
I followed the useful instructions in this thread. I had trouble with the recording of the audio while doing a new screen recording using Quicktime. It was soft. Once I select the multi-output device I can't control the volume of what is playing on the screen. The only way I could get the audio to record at a high level was to set the built-in-output volume controls to maximum in the Audio Device screen. But this meant that whatever was playing on the screen was coming out at full volume through the computers speakers. I was wondering if I was doing something wrong. I am using OS 10.11.6. Thanks.

**Comment by Imanovitz** [comment]
Hi Mattingalls. I see you know a lot about this. And I clearly don't. I have tried a lot of what you guys been talking about. But I don't seem to work for me. If you would, I would really appreciate if you could guide me, or do it for me over TeamViewer?

**Comment by Dams303** [comment]
Hello,
I am running on osx 10.11.6, I have read all the above messages to make sure I have exact same configuration but SoundFlower 2.0b2 can't deliver any sounds in QuickTime input (set on SoundFlower 2ch).
My soundFlower is set with maximum volume on both Output/Input with Mute unchecked. Sample rate set everywhere to 44100. 
 I would like to know if anybody has the same issue? Is there still people with OS X 10.11.6 not able to make SoundFlower to work? A bit lost..
Thanks in advance!

**Comment by PainKiller969** [comment]
@mattingalls I have a problem, I have done everything, I can't hear myself when I talk I can only hear my backround/desktop its so annoying please help.

**Comment by Laniakia** [comment]
@mattingalls I, too, have tried everything, every possible configuration, gone through every one of your answers to every comment, all my settings seem correct, and yet no sound is recorded. I'm on Sierra 10.12.5 and soundflower 2.0b2. Installed & uninstalled and re-started numerous times. Volume is up.  I hear sound when the output is set to the Multi-Output device, yes, with Soundflower & Built-In Output on, but no sound at all in the Quicktime screen recording (which is set to Soundflower & the volume is max). Quicktime 10.4. Been at this for hours, joined GitHub as last resort, leaving a flailing note.

**Comment by mattingalls** [comment]
@Laniakia -- just making sure: so your system default device is set to the Multi-Output?  and the Quicktime "Microphone" input is set to Soundflower?  what if you set the system default device to soundflower -- does Quicktime at least record the audio? (without you being able to monitor)

**Comment by Laniakia** [comment]
@mattingalls Quicktime does not record from Soundflower at all - completely blank. Neither does Audacity. I was trying to find an inexpensive app at the Apple Store to capture video and sound internally, but some of them also rely on Soundflower. I often set a timer in Audacity and use Soundflower to record my friend's radio show. About all I can do is leave the microphone on, I guess.

**Comment by Laniakia** [comment]
@mattingalls I think you have magic with computers - yes, I changed the default device to Soundflower and viola! beautiful sound...! I know I tried this last night but perhaps one of my other settings was off. It's working beautifully now. Thank you!!!!!!!

**Comment by musicspirit** [comment]
Greetings Matt and correspondents on this long and very useful discussion thread!
 - I have installed Soundflower on El Capitan MBP 10.11.5  a couple of time and although it shows up in Audio Set Up as an option, I cannot find the App anywhere on the computer, not in Applications etc and cannot drag it into the dock to boot it up like other applications.  My aim is to record internet radio direct to mp3 ( ideally through Logic X but I dont think it is possible to record to Mp3 directly - I dont want the hassle of converting aiff or wav files after to mp3). All suggestions appreciated. 
PS I would prefer not to install Audacity or any other software if possible - ie use just Logic or Quicktime

**Comment by LightningStalker** [comment]
Thanks guys that fixed it for me.  Somehow, I don't know how, the volume of Soundflower got turned way down, to the point where nothing was coming through.

**Comment by beta-dawg** [comment]
@mattingalls I use external speakers via display port and am unable to control volume on them via my keyboard. So I want soundflower's input to be everything that plays on the system, and soundflower's output to be my external speakers. I have installed the soundflower kernel but where can I change what feeds into soundflower and where does soundflower output? I would want to do this without having to use the old SoundflowerBed app as it has not worked well for me on newer versions of macOS. Thanks!

**Comment by LightningStalker** [comment]
@beta-dawg You can use `Audio MIDI Setup`.

**Comment by beta-dawg** [comment]
@LightningStalker I tried that, it didn't help - I used steps mentioned in this thread somewhere above about creating a multi-output device - it doesn't work for me, unless you have specific steps I should be following.

**Comment by LightningStalker** [comment]
Well, I don't know then. That is how you change the inputs and outputs to Soundflower.

**Comment by DaniZz** [comment]
tells me:

the installation failed (high sierra 10.13.3)

 :/

**Comment by mattingalls** [comment]
the failed message sometimes is just an artifact of the new security in high sierra. did you you do this?
`IF INSTALLING ON HIGH SIERRA
The first attempt to install will display a security alert, then fail. Afterwards, you need to go into System Preferences "Security & Privacy - General" pane and give permission to allow the install signed by the developer "MATT INGALLS". After giving permission, you will be able to run the installer successfully.`

**Comment by foggerwoody** [comment]
tells me:

the installation failed (high sierra 10.13.4)

After I have allow the install in "Security & Privacy"

**Comment by marcelolarios** [comment]
I found a little issue, but return to work:
Is the thing: just have not output sounds in the channel. After some restarts, still not working.
The solution was to just lower the master volume output, which was at maximum and then left at maximum again and just it returned to work...
A tip: for a playback, open a new quicktime in recorder mode and see sound bars shaking.

**Comment by LordMelkor** [comment]
Following the example of recording iTunes with Quicktime I'm able to get it to record properly, however, when Multi-Output Device is selected for sound output, I lose volume control. Is there any way around this?

**Comment by mattingalls** [comment]
@LordMelkor: the only way i know is to adjust the volume of your monitoring device in AudioMIDISetup.  fyi, i do have a solution in the works to transfer volume buttons for soundflower into the monitoring device.
